repos:
  - repo: local
    hooks:
      - id: gofmt
        name: gofmt
        entry: gofmt -s -w
        language: system
        files: '\.go$'

      - id: goimports
        name: goimports (optional)
        entry: goimports -w
        language: system
        files: '\.go$'
        # If goimports is not installed, this hook will fail; users can install it with:
        #   go install golang.org/x/tools/cmd/goimports@latest
